name: Auto Generate Blog
on: [push] # 每次推送代码时触发
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Generator
        run: python3 build_blog.py
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Auto update blog" || echo "No changes to commit"
          git push